In [19]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/diabetes-factors/diabetes-vid.csv

In [20]:
path ='/kaggle/input/diabetes-factors/diabetes-vid.csv'
dt = pd.read_csv(path)
dt.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,dead
1,1,85,66,29,0,26.6,0.351,31,alive
2,8,183,64,0,0,23.3,0.672,32,dead
3,1,89,66,23,94,28.1,0.167,21,alive
4,0,137,40,35,168,43.1,2.288,33,dead

In [21]:
dt.shape

(768, 9)

In [22]:
data = dt
data.loc[:, ['Pregnancies', 'DiabetesPedigreeFunction', 'Age', 'Outcome']]

     Pregnancies  DiabetesPedigreeFunction  Age Outcome
0              6                     0.627   50    dead
1              1                     0.351   31   alive
2              8                     0.672   32    dead
3              1                     0.167   21   alive
4              0                     2.288   33    dead
..           ...                       ...  ...     ...
763           10                     0.171   63   alive
764            2                     0.340   27   alive
765            5                     0.245   30   alive
766            1                     0.349   47    dead
767            1                     0.315   23   alive

[768 rows x 4 columns]

In [23]:
alive = pd.DataFrame(data.loc[data.Outcome == 'alive'])
print(alive)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1              1       85             66             29        0  26.6
3              1       89             66             23       94  28.1
5              5      116             74              0        0  25.6
7             10      115              0              0        0  35.3
10             4      110             92              0        0  37.6
..           ...      ...            ...            ...      ...   ...
762            9       89             62              0        0  22.5
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age Outcome
1                       0.351   31   alive
3                       0.167   21   alive
5                       0.201   30   alive
7                       0.134   29   alive
10                      0.191   30   alive
..                        ...  ...     ...
762                     0.142   33   alive
763                     0.171   63   alive
764                     0.340   27   alive
765                     0.245   30   alive
767                     0.315   23   alive

[500 rows x 9 columns]

In [24]:
alive.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,500.000000,500.0000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,3.298000,109.9800,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
std,3.017185,26.1412,18.063075,14.889947,98.865289,7.689855,0.299085,11.667655
min,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000
25%,1.000000,93.0000,62.000000,0.000000,0.000000,25.400000,0.229750,23.000000
50%,2.000000,107.0000,70.000000,21.000000,39.000000,30.050000,0.336000,27.000000
75%,5.000000,125.0000,78.000000,31.000000,105.000000,35.300000,0.561750,37.000000
max,13.000000,197.0000,122.000000,60.000000,744.000000,57.300000,2.329000,81.000000

In [25]:
alive.BloodPressure.map(lambda b : b >= 68.184).sum()

268

In [26]:
data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000

In [27]:
s = 0
for i in alive.BloodPressure:
    if i >= 68.184:
        s += 1
print(s)

268

In [28]:
data = data.rename(columns = {'Pregnancies': 'grossesses'})
print(data)

     grossesses  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0             6      148             72             35        0  33.6
1             1       85             66             29        0  26.6
2             8      183             64              0        0  23.3
3             1       89             66             23       94  28.1
4             0      137             40             35      168  43.1
..          ...      ...            ...            ...      ...   ...
763          10      101             76             48      180  32.9
764           2      122             70             27        0  36.8
765           5      121             72             23      112  26.2
766           1      126             60              0        0  30.1
767           1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age Outcome
0                       0.627   50    dead
1                       0.351   31   alive
2                       0.672   32    dead
3                       0.167   21   alive
4                       2.288   33    dead
..                        ...  ...     ...
763                     0.171   63   alive
764                     0.340   27   alive
765                     0.245   30   alive
766                     0.349   47    dead
767                     0.315   23   alive

[768 rows x 9 columns]

In [29]:
dead = data.loc[data.Outcome == 'dead']

In [30]:
dead.shape

(268, 9)

In [51]:
dead.Age.mean()
dead.Age.max()
dead.Age.min()
dead.iloc[84, :]

grossesses                      0
Glucose                       177
BloodPressure                  60
SkinThickness                  29
Insulin                       478
BMI                          34.6
DiabetesPedigreeFunction    1.072
Age                            21
Outcome                      dead
Name: 220, dtype: object

In [59]:
dead.describe()
dead.Age.value_counts()

25    14
31    13
41    13
29    13
43    11
22    11
28    10
33    10
38    10
36    10
32     9
27     8
24     8
45     8
26     8
23     7
46     7
52     7
42     7
30     6
40     6
37     6
21     5
44     5
35     5
50     5
51     5
53     4
47     4
34     4
54     4
39     3
58     3
49     3
66     2
62     2
56     2
60     2
59     2
70     1
55     1
61     1
67     1
57     1
48     1
Name: Age, dtype: int64

In [101]:

def tri_Age(tab):
    t = 0
    L = list(tab.Age)
    L_modif = list(tab.Age)
    M = []
    while t < len(L):
        i = min(L)
        M.append(L.index(i))
        L[L.index(i)] = 1000
        t += 1
    return M

#dead.iloc[tri_Age(dead), :]  
print(data)

0      dead
1         1
2      dead
3         1
4      dead
       ...
763       1
764       1
765       1
766    dead
767       1
Name: Outcome, Length: 768, dtype: object

In [118]:
data = pd.read_csv(path)

In [119]:
print(data)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age Outcome
0                       0.627   50    dead
1                       0.351   31   alive
2                       0.672   32    dead
3                       0.167   21   alive
4                       2.288   33    dead
..                        ...  ...     ...
763                     0.171   63   alive
764                     0.340   27   alive
765                     0.245   30   alive
766                     0.349   47    dead
767                     0.315   23   alive

[768 rows x 9 columns]

In [132]:
from sklearn.model_selection import train_test_split
def transfo_outcome(row):
    if row.Outcome == 'alive':
        row.Outcome = 1
    if row.Outcome == 'dead':
        row.Outcome = 0
    return row

data = data.apply(transfo_outcome, axis = 'columns')
#data.Outcome.replace('dead', '0')
print(data)
y = data.Outcome
X = data.drop(['Outcome'], axis = 1)
X = X.select_dtypes(exclude = ['object'])

X_train, X_valid, y_train, y_valid = train_test_split(X, y)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age  Outcome
0                       0.627   50        0
1                       0.351   31        1
2                       0.672   32        0
3                       0.167   21        1
4                       2.288   33        0
..                        ...  ...      ...
763                     0.171   63        1
764                     0.340   27        1
765                     0.245   30        1
766                     0.349   47        0
767                     0.315   23        1

[768 rows x 9 columns]

In [158]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

model = RandomForestRegressor(n_estimators = 10, random_state=0)

model.fit(X_train,y_train)

preds = model.predict(X_valid)


for i in range (len(preds)):
    if preds[i] <= 0.5:
        preds[i]=0
    else:
        preds[i]=1
print(preds)
print(y_valid)
print(mean_absolute_error(preds, y_valid))

[1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1.
 1. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1.
 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0.
 1. 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0.
 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1.
 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1.
 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1.]
287    0
451    0
533    1
271    1
443    0
      ..
128    0
493    0
678    0
290    1
491    1
Name: Outcome, Length: 192, dtype: int64
0.2552083333333333

In [ ]:
from skklearn.pipeline